apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
  - name: vote
    count: 3 

commonAnnotations:
  supported-by: martin.koch@telekom.de

configMapGenerator:
  - name:  vote-options
    envs:
      -  options.env
  
